spring.application.name=planner

# ?? GMAIL SMTP SERVER CONFIGURATION ??
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yakshanth1018@gmail.com
spring.mail.password=eljafzmppqiqusbs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Optional: Keep this as true so you can see if the email sends successfully in the console
spring.mail.properties.mail.debug=true